from PyQt5 import QtCore, QtGui, QtWidgets
import threading
import time
import numpy as np

class Open(object):

    def __init__(self, nst):
        self.nst = nst
        return


    def setupUi(self, MainWindow):
        # Autogenerated code from Qt designer.
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1046, 901)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_content_image = QtWidgets.QLabel(self.centralwidget)
        self.lbl_content_image.setGeometry(QtCore.QRect(90, 10, 201, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_content_image.sizePolicy().hasHeightForWidth())
        self.lbl_content_image.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_content_image.setFont(font)
        self.lbl_content_image.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_content_image.setObjectName("lbl_content_image")
        self.lbl_style_image = QtWidgets.QLabel(self.centralwidget)
        self.lbl_style_image.setGeometry(QtCore.QRect(770, 10, 161, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_style_image.sizePolicy().hasHeightForWidth())
        self.lbl_style_image.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_style_image.setFont(font)
        self.lbl_style_image.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_style_image.setObjectName("lbl_style_image")
        self.btn_file_select_content = QtWidgets.QPushButton(self.centralwidget)
        self.btn_file_select_content.setGeometry(QtCore.QRect(120, 350, 141, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_file_select_content.sizePolicy().hasHeightForWidth())
        self.btn_file_select_content.setSizePolicy(sizePolicy)
        self.btn_file_select_content.setObjectName("btn_file_select_content")
        self.btn_file_select_style = QtWidgets.QPushButton(self.centralwidget)
        self.btn_file_select_style.setGeometry(QtCore.QRect(790, 350, 141, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_file_select_style.sizePolicy().hasHeightForWidth())
        self.btn_file_select_style.setSizePolicy(sizePolicy)
        self.btn_file_select_style.setObjectName("btn_file_select_style")
        self.lbl_generated_image = QtWidgets.QLabel(self.centralwidget)
        self.lbl_generated_image.setGeometry(QtCore.QRect(420, 420, 241, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_generated_image.sizePolicy().hasHeightForWidth())
        self.lbl_generated_image.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_generated_image.setFont(font)
        self.lbl_generated_image.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_generated_image.setObjectName("lbl_generated_image")
        self.btn_file_save_generated = QtWidgets.QPushButton(self.centralwidget)
        self.btn_file_save_generated.setGeometry(QtCore.QRect(460, 770, 141, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_file_save_generated.sizePolicy().hasHeightForWidth())
        self.btn_file_save_generated.setSizePolicy(sizePolicy)
        self.btn_file_save_generated.setObjectName("btn_file_save_generated")
        self.pb_training = QtWidgets.QProgressBar(self.centralwidget)
        self.pb_training.setGeometry(QtCore.QRect(350, 840, 451, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_training.sizePolicy().hasHeightForWidth())
        self.pb_training.setSizePolicy(sizePolicy)
        self.pb_training.setMaximum(1500)
        self.pb_training.setProperty("value", 0)
        self.pb_training.setObjectName("pb_training")
        self.btn_start_file_transfer = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_file_transfer.setGeometry(QtCore.QRect(460, 870, 141, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start_file_transfer.sizePolicy().hasHeightForWidth())
        self.btn_start_file_transfer.setSizePolicy(sizePolicy)
        self.btn_start_file_transfer.setObjectName("btn_start_file_transfer")
        self.plbl_content_image = QtWidgets.QLabel(self.centralwidget)
        self.plbl_content_image.setGeometry(QtCore.QRect(40, 50, 300, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plbl_content_image.sizePolicy().hasHeightForWidth())
        self.plbl_content_image.setSizePolicy(sizePolicy)
        self.plbl_content_image.setText("")
        self.plbl_content_image.setPixmap(QtGui.QPixmap("C:/Users/bende/Pictures/dflt.png"))
        self.plbl_content_image.setObjectName("plbl_content_image")
        self.plbl_style_image = QtWidgets.QLabel(self.centralwidget)
        self.plbl_style_image.setGeometry(QtCore.QRect(710, 40, 300, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plbl_style_image.sizePolicy().hasHeightForWidth())
        self.plbl_style_image.setSizePolicy(sizePolicy)
        self.plbl_style_image.setText("")
        self.plbl_style_image.setPixmap(QtGui.QPixmap("C:/Users/bende/Pictures/dflt.png"))
        self.plbl_style_image.setObjectName("plbl_style_image")
        self.plbl_gen_image = QtWidgets.QLabel(self.centralwidget)
        self.plbl_gen_image.setGeometry(QtCore.QRect(380, 460, 300, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plbl_gen_image.sizePolicy().hasHeightForWidth())
        self.plbl_gen_image.setSizePolicy(sizePolicy)
        self.plbl_gen_image.setText("")
        self.plbl_gen_image.setPixmap(QtGui.QPixmap("C:/Users/bende/Pictures/dflt.png"))
        self.plbl_gen_image.setObjectName("plbl_gen_image")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.custom_ui_changes()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        # Autogenerated code from At Designer.
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NST"))
        self.lbl_content_image.setText(_translate("MainWindow", "Content Image"))
        self.lbl_style_image.setText(_translate("MainWindow", "Style Image"))
        self.btn_file_select_content.setText(_translate("MainWindow", "Choose File..."))
        self.btn_file_select_style.setText(_translate("MainWindow", "Choose File..."))
        self.lbl_generated_image.setText(_translate("MainWindow", "Generated Image"))
        self.btn_file_save_generated.setText(_translate("MainWindow", "Save Image..."))
        self.pb_training.setFormat(_translate("MainWindow", "%p / %m epochs"))
        self.btn_start_file_transfer.setText(_translate("MainWindow", "Begin Style Transfer"))

    def custom_ui_changes(self):
        """
        Apply custom changes to UI not made in Qt Designer.
        :return:
        """
        self.pb_training.setFormat("%p%")
        self.pb_training.setMaximum(100)
        self.btn_file_select_content.clicked.connect(self.get_content_filename)
        self.btn_file_select_style.clicked.connect(self.get_style_filename)
        self.btn_start_file_transfer.clicked.connect(self.start_nst)
        return

    def start_nst(self):
        """
        Begin neural style-transfer with selected content and style images.
        :return:
        """
        if(self.nst.CONTENT_PATH is None or self.nst.STYLE_PATH is None):
            err = QtWidgets.QMessageBox(self.centralwidget)
            err.setIcon(QtWidgets.QMessageBox.Critical)
            err.setText("Error")
            err.setInformativeText("Either content image or style image is not selected.")
            err.setWindowTitle("Error")
            err.show()
            return
        self.btn_start_file_transfer.setEnabled(False)
        self.btn_file_save_generated.setEnabled(False)
        thread = threading.Thread(target=self.nst.neural_style_transfer,
                                  args=(self.nst.CONTENT_PATH, self.nst.STYLE_PATH))
        ui_thread = threading.Thread(target=self.update_nst_ui)
        thread.start()
        ui_thread.start()
        return

    def update_nst_ui(self):
        self.pb_training.reset()
        while(self.nst.EPOCH_COMPLETE < 1):
            time.sleep(5)
        while (self.nst.EPOCH_COMPLETE < self.nst.MAX_EPOCH - 1):
            self.pb_training.setValue((self.nst.EPOCH_COMPLETE/self.nst.MAX_EPOCH) * 100)
            latest_gen = self.nst.LATEST_GEN
            lg_clip = np.clip(latest_gen[0], 0, 255).astype('uint8')
            height, width, channel = lg_clip.shape
            qimg = QtGui.QImage(lg_clip.data, width, height, 3 * width, QtGui.QImage.Format_RGB888)
            self.plbl_gen_image.setPixmap(QtGui.QPixmap(qimg).scaled(300, 300, QtCore.Qt.IgnoreAspectRatio))
            time.sleep(1)
        self.pb_training.setValue(self.pb_training.maximum())
        self.btn_start_file_transfer.setEnabled(True)
        self.btn_file_save_generated.setEnabled(True)
        return


    def get_content_filename(self):
        self.nst.CONTENT_PATH = self.open_file_dialog()
        pixmap = QtGui.QPixmap(self.nst.CONTENT_PATH)
        pixmap = pixmap.scaled(300, 300, QtCore.Qt.IgnoreAspectRatio)
        self.plbl_content_image.setPixmap(pixmap)
        return

    def get_style_filename(self):
        self.nst.STYLE_PATH = self.open_file_dialog()
        pixmap = QtGui.QPixmap(self.nst.STYLE_PATH)
        pixmap = pixmap.scaled(300, 300, QtCore.Qt.IgnoreAspectRatio)
        self.plbl_style_image.setPixmap(pixmap)
        return

    def open_file_dialog(self):
        filename, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Open File",
                                                            "", "Image Files (*.png *.jpg *.jpeg)")
        return filename
